<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MicMeter.Audio.Windows</AssemblyName>
    <RootNamespace>MicMeter.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicMeter.Audio.Abstractions\MicMeter.Audio.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.3.0" />
  </ItemGroup>
</Project>
